// Subset of the real manifest, enriched with per-reading progress state for the prototype.
// "Today" in this prototype = 2026-04-21 (matches repo publish_cutoff_date).

window.SITE = {
  title: "2026-1 성인발달과노화",
  subtitle: "성인발달과노화 읽기 사이트",
  tagline: "수업 날짜 순서대로 읽고, 정리와 퀴즈까지 한 흐름으로 이어 보는 학습 공간.",
  today: "2026-04-21",
  student: { name: "수강생", course_code: "2026-1" },
};

// progress: fraction 0..1 per stage: read, concepts, quiz, prep
// state: "ready" | "locked" | "current"
window.READINGS = [
  {
    slug: "ch01-gerontology",
    title: "노년학의 발달과 학문적 성격",
    subtitle: "노년학의 성립, 학문적 성격, 연령과 노인 개념을 정리하는 입문 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH1",
    lang: "한국어",
    year: 2019,
    class_date: "2026-03-05",
    display_date_label: "3/05",
    week: 1,
    tags: ["노년학", "연령 개념", "교재"],
    state: "ready",
    progress: { read: 1, concepts: 1, quiz: 1, prep: 1 },
    overview_hook:
      "이 장은 노년학이 단순히 노인의학이 아니라 노화과정과 노인 집단을 함께 다루는 다학제적 학문이며, 65세 기준도 자연법칙이 아니라 사회적으로 만들어진 구분임을 먼저 잡게 만든다.",
    classroom_points: [
      "Gerontology는 노인의학만을 뜻하는 말이 아니라 노화과정과 노인 집단을 함께 연구하는 넓은 학문이다.",
      "노년학은 오래된 학문이 아니고, 서구도 1940년대 이후 연구소·학회·학술지가 생기며 본격화되었다.",
      "한국에서는 1970년대 이후 노인문제 대응과 고령화의 가시화 속에서 노년학이 자리 잡기 시작했다.",
      "노년학은 생물학, 심리학, 사회학, 가족학, 정책연구가 함께 들어오는 다학제적 응용학문이다.",
      "65세 기준은 과학적 경계라기보다 비스마르크 연금 제도와 사회보장 제도의 역사적 관행에 가깝다.",
      "같은 65세라도 생물학적·사회적·심리적·기능적 연령이 달라 노인을 동질 집단으로 보면 안 된다.",
    ],
  },
  {
    slug: "ch02-gerontology",
    title: "인구고령화와 노년기 발달",
    subtitle: "인구변천, 한국의 고령화 속도, 고령화의 사회적 결과를 연결하는 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH2",
    lang: "한국어",
    year: 2019,
    class_date: "2026-03-10",
    display_date_label: "3/10",
    week: 2,
    tags: ["인구고령화", "한국사회", "교재"],
    state: "locked",
    progress: { read: 0, concepts: 0, quiz: 0, prep: 0 },
  },
  {
    slug: "beck-2016",
    title: "When Are You Really an Adult?",
    subtitle: "성인 이행을 법·생물학·사회 역할·책임의 관점에서 다시 묻는 The Atlantic 기사.",
    authors_display: "Julie Beck",
    type_label: "기사",
    lang: "영어",
    year: 2016,
    class_date: "2026-03-12",
    display_date_label: "3/12",
    week: 2,
    tags: ["성인 이행", "Emerging Adulthood", "기사"],
    state: "ready",
    progress: { read: 1, concepts: 0.6, quiz: 0, prep: 0 },
  },
  {
    slug: "ch03-gerontology",
    title: "노년학의 주요이론 및 관점",
    subtitle: "메타이론, 전생애발달, 생애과정, 사회노년학 이론을 정리하는 이론 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH3",
    lang: "한국어",
    year: 2019,
    class_date: "2026-03-17",
    display_date_label: "3/17",
    week: 3,
    tags: ["이론", "전생애발달", "교재"],
    state: "locked",
    progress: { read: 0, concepts: 0, quiz: 0, prep: 0 },
  },
  {
    slug: "ch04-gerontology",
    title: "노년학 연구방법",
    subtitle: "연령차이 해석, 양적 연구, 질적 연구를 비교하는 방법론 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH4",
    lang: "한국어",
    year: 2019,
    class_date: "2026-03-19",
    display_date_label: "3/19",
    week: 3,
    tags: ["연구방법", "연령효과", "교재"],
    state: "locked",
    progress: { read: 0, concepts: 0, quiz: 0, prep: 0 },
  },
  {
    slug: "hulur-et-al-2019",
    title: "Cohort Differences in Cognitive Aging: The Role of Perceived Work Environment",
    subtitle: "교육만이 아니라 성인기 노동환경이 코호트별 인지노화 차이에 어떻게 연결되는지 다루는 논문.",
    authors_display: "Hülür, Ram, Willis, Schaie, Gerstorf",
    type_label: "논문",
    lang: "영어",
    year: 2019,
    class_date: "2026-03-24",
    display_date_label: "3/24",
    week: 4,
    tags: ["인지노화", "코호트", "노동환경"],
    state: "ready",
    progress: { read: 1, concepts: 1, quiz: 0.66, prep: 0.4 },
    overview_hook:
      "이 논문은 교육 수준만으로 설명해 온 코호트별 인지 차이가 실제로는 성인기 노동환경의 변화와도 연결되는지 묻는다.",
    classroom_points: [
      "후기 코호트가 모든 능력에서 더 나았던 것은 아니며, number ability는 오히려 낮았다.",
      "저자들은 교육 효과를 통제한 뒤에도 work control과 work innovation이 인지 수행과 연결된다고 본다.",
      "코호트 비교는 출생연도 자체보다 age와 retest를 맞춘 관측치 단위 매칭으로 설계되었다.",
      "노동환경 변수는 직업 복잡도 일반척도가 아니라 work control·autonomy·innovation으로 나뉜다.",
      "관찰연구이기 때문에 더 좋은 노동환경이 인지를 높였는지, 원래 인지가 높은 사람이 그런 일을 택했는지는 분리하지 못한다.",
    ],
  },
  {
    slug: "ch05-gerontology",
    title: "신체적 노화",
    subtitle: "생물학적 노화 설명과 노년기 신체 변화, 질병과의 구분을 다루는 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH5",
    lang: "한국어",
    year: 2019,
    class_date: "2026-03-26",
    display_date_label: "3/26",
    week: 4,
    tags: ["신체적 노화", "생물학", "교재"],
    state: "ready",
    progress: { read: 1, concepts: 1, quiz: 1, prep: 0.8 },
    overview_hook:
      "이 장은 인간의 최대수명이 어디까지 갈 수 있는지라는 질문에서 출발해, 정상노화와 병리, 불가피한 변화와 개입 가능한 변화를 구분하게 만든다.",
    classroom_points: [
      "평균수명이 늘어나는 것과 최대수명이 늘어나는 것은 같은 말이 아니다.",
      "일차적 노화는 보편적이고 불가피하지만, 이차적 노화는 질병·불용·남용과 얽혀 있어 지연할 여지가 있다.",
      "프로그램 이론과 손상·오류 이론은 배타적 정답이라기보다 서로 다른 설명 축으로 읽는 편이 안전하다.",
      "외형 변화만이 아니라 심혈관·호흡·신경·감각기관 변화까지 함께 봐야 노년기 신체 변화를 제대로 설명할 수 있다.",
      "실천적 메시지는 정상노화와 질병을 구분하고, 운동·식이·금연·환경 관리 같은 개입 가능성을 놓치지 않는 데 있다.",
    ],
  },
  {
    slug: "olshansky-carnes-2019",
    title: "Inconvenient Truths About Human Longevity",
    subtitle: "급진적 수명연장보다 건강수명 연장에 초점을 옮겨야 한다는 리뷰 논문.",
    authors_display: "S. J. Olshansky, B. A. Carnes",
    type_label: "기사",
    lang: "영어",
    year: 2019,
    class_date: "2026-03-31",
    display_date_label: "3/31",
    week: 5,
    tags: ["longevity", "healthspan", "review"],
    state: "ready",
    progress: { read: 1, concepts: 0.5, quiz: 0, prep: 0 },
  },
  {
    slug: "kerrigan-2018",
    title: "12 Innovations That Could Make Reverse Aging a Reality",
    subtitle: "역노화를 둘러싼 12개 기술을 대중적으로 소개하는 웹 기사.",
    authors_display: "Saoirse Kerrigan",
    type_label: "기사",
    lang: "영어",
    year: 2018,
    class_date: "2026-03-31",
    display_date_label: "3/31",
    week: 5,
    tags: ["reverse aging", "popular science", "기사"],
    state: "ready",
    progress: { read: 0.3, concepts: 0, quiz: 0, prep: 0 },
  },
  {
    slug: "ch06-gerontology",
    title: "심리적 노화 I : 인지적 변화",
    subtitle: "지능, 기억, 지혜와 창의력을 중심으로 인지적 노화를 정리하는 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH6",
    lang: "한국어",
    year: 2019,
    class_date: "2026-04-02",
    display_date_label: "4/02",
    week: 6,
    tags: ["인지적 노화", "지능", "기억"],
    state: "ready",
    progress: { read: 1, concepts: 1, quiz: 0.33, prep: 0 },
  },
  {
    slug: "ch07-gerontology",
    title: "심리적 노화 II : 성격 및 정서",
    subtitle: "성격의 안정성과 변화, 자아발달, 정서 변화와 적응을 다루는 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH7",
    lang: "한국어",
    year: 2019,
    class_date: "2026-04-09",
    display_date_label: "4/09",
    week: 7,
    tags: ["성격", "정서", "적응"],
    state: "ready",
    progress: { read: 1, concepts: 0.4, quiz: 0, prep: 0 },
  },
  {
    slug: "ch08-gerontology",
    title: "사회적 노화 I: 중노년기 세대관계 및 친족관계",
    subtitle: "노부모-성인자녀, 조부모-손자녀, 노년기 형제관계를 다세대 맥락에서 읽는 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH8",
    lang: "한국어",
    year: 2019,
    class_date: "2026-04-21",
    display_date_label: "4/21",
    week: 8,
    tags: ["세대관계", "친족관계", "중노년기"],
    state: "current",
    progress: { read: 0.2, concepts: 0, quiz: 0, prep: 0 },
    overview_hook:
      "수명 연장과 저출산이 결합할 때 세대 간 지원과 긴장이 어떻게 재구성되는지 정리한다.",
    classroom_points: [
      "성인자녀-노부모 관계는 거리감 있는 친밀성으로 설명된다.",
      "조부모-손자녀 관계는 대리 양육부터 의례적 관계까지 스타일이 갈린다.",
      "형제관계는 생애 마지막까지 이어지는 가장 긴 가족관계다.",
    ],
  },
  {
    slug: "ch09-gerontology",
    title: "사회적 노화 II: 중노년기 부부관계",
    subtitle: "결혼의 의미, 길어진 부부기간, 노년기 이혼과 사별을 함께 다루는 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH9",
    lang: "한국어",
    year: 2019,
    class_date: "2026-04-28",
    display_date_label: "4/28",
    week: 9,
    tags: ["부부관계", "결혼", "사별"],
    state: "locked",
    progress: { read: 0, concepts: 0, quiz: 0, prep: 0 },
  },
  {
    slug: "blieszner-2014",
    title: "The Worth of Friendship: Can Friends Keep Us Happy and Healthy?",
    subtitle: "노년기 친구관계의 정의·기능·건강효과·실천적 활용을 정리한 리뷰.",
    authors_display: "Rosemary Blieszner",
    type_label: "기사",
    lang: "영어",
    year: 2014,
    class_date: "2026-05-07",
    display_date_label: "5/07",
    week: 10,
    tags: ["friendship", "well-being", "later life"],
    state: "locked",
    progress: { read: 0, concepts: 0, quiz: 0, prep: 0 },
  },
  {
    slug: "ch11-gerontology",
    title: "노년기 일과 은퇴",
    subtitle: "노년기 노동의 의미, 은퇴 적응, 은퇴준비교육을 함께 다루는 장.",
    authors_display: "한경혜 외",
    type_label: "노년학 CH11",
    lang: "한국어",
    year: 2019,
    class_date: "2026-05-12",
    display_date_label: "5/12",
    week: 11,
    tags: ["일", "은퇴", "노년기 노동"],
    state: "locked",
    progress: { read: 0, concepts: 0, quiz: 0, prep: 0 },
  },
];

// --- Concepts and quiz content for the ch08 deep-dive (current week) ---
window.READING_DETAILS = {
  "ch08-gerontology": {
    concepts: [
      {
        term: "거리감 있는 친밀성",
        ko: "intimacy at a distance",
        body:
          "성인자녀와 노부모가 서로 독립된 가구에 살면서도 정서적으로 가깝게 지내는 관계 양식. 물리적 거리와 정서적 밀도가 반드시 반비례하지 않는다는 점을 보여 준다.",
        anchors: ["p.214", "p.221"],
      },
      {
        term: "상호 교환 관점",
        ko: "intergenerational solidarity",
        body:
          "세대 간 관계를 정서·기능·재정·접촉의 다축 교환으로 보는 분석틀. 일방적 부양 논의 대신 서로 주고받는 양상을 본다.",
        anchors: ["p.218"],
      },
      {
        term: "조부모 역할 스타일",
        ko: "grandparenting styles",
        body:
          "공식적(formal)·재미 추구(fun-seeker)·대리 부모(surrogate)·지혜 전수(reservoir of wisdom)·원거리(distant)로 나뉘는 다섯 유형. 한국 맥락에서는 대리 양육 비중이 여전히 높다.",
        anchors: ["p.229"],
      },
      {
        term: "생애 가장 긴 관계로서의 형제",
        ko: "sibling tie across the life course",
        body:
          "형제 관계는 출생부터 사망까지 이어지는 경우가 많아 전 생애에서 가장 긴 가족관계가 된다. 노년기에는 정서적 지지가 상대적으로 중요해진다.",
        anchors: ["p.235"],
      },
    ],
    quiz: [
      {
        kind: "OX",
        q: "성인자녀와 노부모 사이의 ‘거리감 있는 친밀성’은 물리적 거리가 멀수록 정서적 거리도 멀어진다는 개념이다.",
        a: "X",
        explain:
          "반대다. 물리적 거리와 정서적 밀도는 반드시 반비례하지 않는다는 점을 설명하는 개념이다.",
      },
      {
        kind: "OX",
        q: "세대 간 관계의 상호 교환 관점은 정서·기능·재정·접촉을 별도의 축으로 본다.",
        a: "O",
        explain: "다축 교환으로 보는 것이 핵심이다.",
      },
      {
        kind: "단답",
        q: "Neugarten과 Weinstein이 분류한 조부모 역할 스타일 중, 손자녀의 일상 양육을 실질적으로 맡는 유형은?",
        a: "대리 부모(surrogate)",
      },
    ],
  },
};

window.TIMELINE = [
  { week: 1, date_range: "3/05", label: "입문" },
  { week: 2, date_range: "3/10–12", label: "고령화·성인 이행" },
  { week: 3, date_range: "3/17–19", label: "이론·방법" },
  { week: 4, date_range: "3/24–26", label: "신체·인지" },
  { week: 5, date_range: "3/31", label: "수명·역노화" },
  { week: 6, date_range: "4/02", label: "인지적 노화" },
  { week: 7, date_range: "4/09", label: "성격과 정서" },
  { week: 8, date_range: "4/21", label: "세대관계", current: true },
  { week: 9, date_range: "4/28", label: "부부관계" },
  { week: 10, date_range: "5/07", label: "친구·이웃" },
  { week: 11, date_range: "5/12", label: "일과 은퇴" },
];
